In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as ss

In [2]:
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', None)

In [3]:
# #get rid of scientific notation
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [4]:
# failed sound check 1957441

# Fish

In [5]:
# import file
data = pd.read_csv('data_exp_27347-v3_task-d7fe.csv', sep = ",")
# data_2 = pd.read_csv("pilot_2/data_exp_24005-v8_task-lhx6.csv", sep = ",")


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [6]:
data.task.unique()

array([nan, 'fishing_control', 'mood_rating_control'], dtype=object)

In [7]:
data = data.replace('null', np.nan)
data  = data.replace('nan', np.nan)


In [8]:
data['start_time'] = round(data['start_time'].astype(float))

In [9]:
data = data[['Participant Private ID', 'UTC Timestamp','key pressed', 'price_displayed', 'environment', 'task', 'function id',
       'builtin rt', 'end_time', 'start_time', 'response', 'round_instance']]


In [10]:
data.rename(columns={"Participant Private ID": "Subject"}, inplace = True)


In [11]:
data = data.sort_values(by = ['Subject', 'start_time'])

In [12]:
data['trial_label'] = data[['environment', 'round_instance']].apply(lambda x: ' '.join(x.astype(str)), axis=1)


In [13]:
# exclude
# data = data[data.Subject != 1972447]

In [14]:
data["environment_binary"] = np.where(data["environment"] == 'pre_mood', 0, 1)

In [15]:
data["mood"] = data["task"].map({"mood_rating_pos":"pos",
                                    "mood_rating_neg":"neg"})

In [16]:
data = data.sort_values(by = ["Subject", "UTC Timestamp"])

In [17]:
data.reset_index(inplace = True)

In [18]:
data.Subject.nunique()

30

# Latency

In [19]:
fish = data[(data.task == "fishing_pos")|(data.task == "fishing_neg")|(data.task == "fishing_control")]



In [20]:
fish = fish[fish['start_time'].notna()]

In [21]:
fish['start_time'] = fish['start_time'].astype(int)

In [22]:
fish.environment.unique()

array(['pre_mood', 'post_mood'], dtype=object)

In [23]:
d = fish.groupby(['Subject','environment_binary', 'round_instance'])['start_time'].diff().shift(-1).reset_index(name = 'latency')
d = d.set_index('index')


In [24]:
fish['latency'] = d['latency']
fish = fish.sort_index().sort_values(['Subject', 'start_time'])

In [25]:
def mask_first(x):
    """
    get rid of the first spike by creating a mask of 0, 1, 1, 1, ...
    """
    result = np.ones_like(x)
    result[0] = 0
    return result

In [26]:
mask = fish.groupby(['Subject', 'environment'])['round_instance'].transform(mask_first).astype(bool)

# data_useful = data_useful.loc[mask]


In [27]:
fish = fish.loc[mask]

In [28]:
fish.head()
fish["mood"] = fish["task"].map({'fishing_pos': "pos", 'fishing_neg':'neg', 'fishing_control':'control'})


In [29]:
fish.groupby("mood")["Subject"].nunique()

mood
control    30
Name: Subject, dtype: int64

In [30]:
fish['mood'].unique()

array(['control'], dtype=object)

In [31]:
fish.latency.isnull().values.any()
fish = fish[fish.latency.notnull()]

In [32]:
# mad
fish.shape

(57955, 17)

In [33]:
median = np.median(fish.latency)
low = median - 3*ss.median_absolute_deviation(fish.latency)
above = median + 3*ss.median_absolute_deviation(fish.latency)
fish = fish[(fish.latency>=low)&(fish.latency<=above)]

In [34]:
# mad
fish.shape

(54682, 17)

# Rating

In [35]:
data.task.unique()

array([nan, 'fishing_control', 'mood_rating_control'], dtype=object)

In [36]:
# response
rating = data[(data.task == "mood_rating_pos")|(data.task == "mood_rating_neg")|(data.task == "mood_rating_control")]


In [37]:
rating = rating[rating['response'].notna()]

# Concat 

In [38]:
rating["latency"] = np.nan*len(rating)

In [39]:
data_complete = pd.concat([rating, fish])


In [40]:
data_complete = data_complete.sort_values(by = "index")

# Backfilling

In [41]:
data_complete["response"].bfill(inplace = True)

# df.bfill(axis ='rows')


In [42]:
data_complete["block"] = data_complete["round_instance"].map({
    1:"1st",
    2:"1st",
    3:"1st",
    4:"1st",
    5:"2nd",
    6:"2nd",
    7:"2nd",
    8:"2nd",
    9:"3rd",
    10:"3rd",
    11:"3rd",
    12:"3rd"
})

In [43]:
data_complete.to_csv("data_control_oct_1_latency_backfilled_happiness.csv")


In [44]:
data.price_displayed.unique()

array([nan, 1.8, 0.7, 0.1, 2.5, 1.2, 0.3])

In [45]:
data.head(100)

index     Subject     UTC Timestamp  key pressed  price_displayed  \
0       0 2035451.000 1601568572170.000          nan              nan   
1       1 2035451.000 1601568572232.000          nan              nan   
2       2 2035451.000 1601568572232.000          nan              nan   
3       3 2035451.000 1601568572232.000          nan              nan   
4       4 2035451.000 1601568573064.000       40.000            1.800   
5       5 2035451.000 1601568573206.000       40.000            1.800   
6       6 2035451.000 1601568573331.000       40.000            1.800   
7       7 2035451.000 1601568573473.000       40.000            1.800   
8       8 2035451.000 1601568573598.000       40.000            1.800   
9       9 2035451.000 1601568573754.000       40.000            1.800   
10     10 2035451.000 1601568573910.000       40.000            1.800   
11     11 2035451.000 1601568574222.000       40.000            1.800   
12     12 2035451.000 1601568574222.000       40.000            1.800   
13     13 2035451.000 1601568574349.000       40.000            1.800   
14     14 2035451.000 1601568574458.000       40.000            1.800   
15     15 2035451.000 1601568574599.000       40.000            1.800   
16     16 2035451.000 1601568574740.000       40.000            1.800   
17     17 2035451.000 1601568574896.000       40.000            1.800   
18     18 2035451.000 1601568575037.000       40.000            1.800   
19     19 2035451.000 1601568575380.000       40.000            1.800   
20     20 2035451.000 1601568575474.000       40.000            1.800   
21     21 2035451.000 1601568575770.000       40.000            1.800   
22     22 2035451.000 1601568575770.000       40.000            1.800   
23     23 2035451.000 1601568575895.000       40.000            1.800   
24     24 2035451.000 1601568576021.000       40.000            1.800   
25     25 2035451.000 1601568576176.000       40.000            1.800   
26     26 2035451.000 1601568576291.000       40.000            1.800   
27     27 2035451.000 1601568576450.000       40.000            1.800   
28     28 2035451.000 1601568576577.000       40.000            1.800   
29     29 2035451.000 1601568576718.000       40.000            1.800   
30     30 2035451.000 1601568576842.000       40.000            1.800   
31     31 2035451.000 1601568576984.000       40.000            1.800   
32     32 2035451.000 1601568577125.000       40.000            1.800   
33     33 2035451.000 1601568577266.000       40.000            1.800   
34     34 2035451.000 1601568577396.000       40.000            1.800   
35     35 2035451.000 1601568577536.000       40.000            1.800   
36     36 2035451.000 1601568577662.000       40.000            1.800   
37     37 2035451.000 1601568577817.000       40.000            1.800   
38     38 2035451.000 1601568577943.000       40.000            1.800   
39     39 2035451.000 1601568578114.000       40.000            1.800   
40     40 2035451.000 1601568578209.000       40.000            1.800   
41     41 2035451.000 1601568578370.000       40.000            1.800   
42     42 2035451.000 1601568578528.000       40.000            1.800   
43     43 2035451.000 1601568578652.000       40.000            1.800   
44     44 2035451.000 1601568578793.000       40.000            1.800   
45     45 2035451.000 1601568578949.000       40.000            1.800   
46     46 2035451.000 1601568579090.000       40.000            1.800   
47     47 2035451.000 1601568579231.000       40.000            1.800   
48     48 2035451.000 1601568579391.000       40.000            1.800   
49     49 2035451.000 1601568579518.000       40.000            1.800   
50     50 2035451.000 1601568579660.000       40.000            1.800   
51     51 2035451.000 1601568579799.000       40.000            1.800   
52     52 2035451.000 1601568579924.000       40.000            1.800   
53     53 2035451.000 1601568580065.000       40.000          